 
//AUTO GENERATED By gen_main.go, DO NOT EDIT
package main

import (
	"github.com/andodeki/api.gen_test.com/src/util"
	"github.com/andodeki/api.gen_test.com/src/config"
	"github.com/andodeki/api.gen_test.com/src/datasources"
	"github.com/andodeki/api.gen_test.com/src/queue"
	"github.com/andodeki/api.gen_test.com/src/httpServer"
	
)
func runHttpServer(
	logger *util.Logger,
	cfg *config.Config,
	emailInAppQueue queue.EmailQueueInterface,
	client *datasources.DatabaseClient,
	rdb *datasources.RedisClient,
	sdb *datasources.ScyllaDBClient,
	metrics http.Handler,
	/*, statisticsInstance statistics.Statistics*/
) (srv *httpServer.HttpServer) {

	return srv
}	
