package gen_startup

import (
	"fmt"

	"github.com/andodeki/gen_project/aOK_GenerateCode/dir"
	"github.com/andodeki/gen_project/aOK_GenerateCode/project"
)

var HTTPServerImports = []string{
	"src/util",
	"src/config",
	"src/datasources",
	"src/queue",
	"src/httpServer",
}

func Generate_HTTPServerImportsContents() {
	header = ` 
//AUTO GENERATED By gen_main.go, DO NOT EDIT
package main

import (
	%s
)
func runHttpServer(
	logger *util.Logger,
	cfg *config.Config,
	emailInAppQueue queue.EmailQueueInterface,
	client *datasources.DatabaseClient,
	rdb *datasources.RedisClient,
	sdb *datasources.ScyllaDBClient,
	metrics http.Handler,
	/*, statisticsInstance statistics.Statistics*/
) (srv *httpServer.HttpServer) {

	return srv
}	
`
	// HTTPServerImports = append(HTTPServerImports, dir.DatasourcesFiles...)
	sb := dir.FormStringDir(project.ProjectName, HTTPServerImports)

	startup_ := fmt.Sprintf(header, sb.String())
	dir.Create_Files(startup_, "httpServer.go")

}
